services:
  - type: web
    name: profit-prediction-ml-project
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.address 0.0.0.0 --server.port $PORT
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
