services:
  - type: web
    name: profit-prediction-ml-project
    env: python
    rootDir: flask-app
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
